// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Prestamo", b =>
                {
                    b.Property<long>("idPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idPrestamo"));

                    b.Property<DateTime>("fchPrestamo")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("idPrestamo");

                    b.ToTable("prestamos");
                });

            modelBuilder.Entity("DAL.Rel_Vajilla_Prestamo", b =>
                {
                    b.Property<long>("idRelVajillaPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idRelVajillaPrestamo"));

                    b.Property<long>("idPrestamo")
                        .HasColumnType("bigint");

                    b.Property<long>("idVajilla")
                        .HasColumnType("bigint");

                    b.HasKey("idRelVajillaPrestamo");

                    b.HasIndex("idPrestamo");

                    b.HasIndex("idVajilla");

                    b.ToTable("rel_Vajillas_Prestamos");
                });

            modelBuilder.Entity("DAL.Vajilla", b =>
                {
                    b.Property<long>("idVajilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("idVajilla"));

                    b.Property<int>("cantidadVajilla")
                        .HasColumnType("integer");

                    b.Property<string>("codigoVajilla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcionVajilla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombreVajilla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idVajilla");

                    b.ToTable("vajillas");
                });

            modelBuilder.Entity("DAL.Rel_Vajilla_Prestamo", b =>
                {
                    b.HasOne("DAL.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("idPrestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Vajilla", "Vajilla")
                        .WithMany()
                        .HasForeignKey("idVajilla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");

                    b.Navigation("Vajilla");
                });
#pragma warning restore 612, 618
        }
    }
}
